### ISSUE TITLE
Chose between `actix` and `axum`

### ISSUE THREAD

**Issue by renan061** [cartesi/rollups#152] opened 2023-07-10 17:02 UTC
## 📚 Context

We are using both `actix` and `axum`, two libraries that do roughly the same thing.

## ✔️ Solution

We should change the code to only use `actix`.

**Comment by torives** [comment] 2023-07-11 20:33
Isn't this a duplicate of #86?

**Comment by gligneul** [comment] 2023-07-11 20:51
> Isn't this a duplicate of https://github.com/cartesi/rollups/issues/86?

Yes. Closing this one.

**Closed by gligneul** 2023-07-11 20:51 UTC
Labels: feature, offchain
